const mongoose = require('mongoose')

const Phrase = mongoose.Schema({
    English: String,
    Afrikaans: String,
    Irish: String,
    Albanian: String,
    Italian: String,
    Arabic: String,
    Arabic_romanized: String,
    Japanese: String,
    Japanese_romanized: String,
    Korean: String,
    Korean_romanized: String,
    Chinese: String,
    Chinese_romanized: String,
    Malay: String,
    Norwegian: String,
    Persian: String,
    Persian_romanized: String,
    Portuguese: String,
    Danish: String,
    Esperanto: String,
    Filipino: String,
    Spanish: String,
    Hindi: String,
    Hindi_romanized: String,
    Urdu: String,
    Urdu_romanized: String,
    Vietnamese: String,
    Indonesian: String,
    Icelandic: String,
    Greek: String,
    Greek_romanized: String,
    Thai: String,
    Thai_romanized: String,
    Russian: String,
    Russian_romanized: String,
    category: {
        type: String,
        enum: ["starting phrases", "gym", "nature"],
        required: [true, "Category is a required field."]
    },
    owner: mongoose.Schema.ObjectId,
})

module.exports = mongoose.model("Phrase", Phrase)